CREATE TABLE EVENT(
EVENT_ID INT PRIMARY KEY,
EVENT_NAME_ VARCHAR(255),
EVENT_DATE DATETIME
);
CREATE TABLE ATTENDEE(
EVENT_ID INT ,
ATTENDEE_ID INT PRIMARY KEY, 
NAME_ VARCHAR(255),
NUMBERS INT,
FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);
CREATE TABLE VENUE(
VENUE_ID INT PRIMARY KEY,
VENUE_NAME_ VARCHAR(255),
CAPACITYS INT
);
CREATE TABLE VENDOR(
VENDOR_ID INT PRIMARY KEY,
NAME_ VARCHAR(255)
);
CREATE TABLE TASK(
TASK_ID INT PRIMARY KEY,
EVENT_ID INT ,
NAME_ VARCHAR(255),
FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);
CREATE TABLE SCHEDULE(
SCHEDULE_ID INT PRIMARY KEY,
START_DATE DATETIME,
END_TIME DATETIME,
EVENT_ID INT ,
FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);
CREATE TABLE BUDGET(
BUDGET_ID INT,
TOTAL_BUDGET DECIMAL(10,2),
EVENT_ID INT ,
FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);
CREATE TABLE PAYMENT (
    PAYMENT_ID INT PRIMARY KEY,
    ATTENDEE_ID INT,
    PAYMENT_AMOUNT DECIMAL(10,2),
    PAYMENT_DATE DATETIME,
    FOREIGN KEY (ATTENDEE_ID) REFERENCES ATTENDEE(ATTENDEE_ID)
);
CREATE TABLE EVENT_ORGANIZER (
    ORGANIZER_ID INT PRIMARY KEY,
    NAME_ VARCHAR(255),
    EVENT_ID INT,
    ROLE_ VARCHAR(255),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);
CREATE TABLE EVENT_TYPE (
    EVENT_TYPE_ID INT PRIMARY KEY,
    TYPE_NAME_ VARCHAR(255),
    EVENT_ID INT,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
);